config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "registrations" }
  #devise_for :users
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'movies' => 'movies#index'
get 'movie' => 'movies#single'
get 'genre' => 'movies#genre'
get 'profile' => 'profiles#profile'
post 'addmovie' => 'users#addmovie', as: 'addmovie'
post 'top_movies' => 'users#top_movies', as: 'top_movies'
root 'movies#home'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
# Get Movies
    @query = ""
    if params[:keyword].present?
    @query= [params[:keyword]]
    else
    @query = ["a"]
    end
    @query_string = @query[0]
    @query = @query.to_s.gsub(/\s/, '%20')
    base_url = "https://api.themoviedb.org/3"
    endpoint = "search/movie"
    @key = "2517708c8fb4b77b5994719f8007a06d"
    api_url = "#{base_url}/#{endpoint}?api_key=#{@key}&query=#{@query}&language=en-US&include_adult=false"
    require "http"
    @response = HTTP.get(api_url).body
#get genre array
    genre_api_url = "https://api.themoviedb.org/3/genre/movie/list?api_key=2517708c8fb4b77b5994719f8007a06d&language=en-US"
    @genre = JSON.parse(HTTP.get(genre_api_url).body)
  end

  def single

    @base_url = "https://api.themoviedb.org/3"
    @key = "2517708c8fb4b77b5994719f8007a06d"

    #Get Credits
     @title= [params[:title]]
     @single_movie_id= [params[:id]]
     @single_movie_id = @single_movie_id[0]
     endpoint = "movie/#{@single_movie_id}/credits"
     api_url = "#{@base_url}/#{endpoint}?api_key=#{@key}&query=#{@query}"
     require "http"
     @cast = HTTP.get(api_url).body

 #Get Video Link
     endpoint = "movie/#{@single_movie_id}/videos"
     api_uri = "#{@base_url}/#{endpoint}?api_key=#{@key}&query=#{@query}&language=en-US"
     require "http"
     @videos = HTTP.get(api_uri).body

 # Get Single Movie

        @single_movie_id_number = [params[:id]]
        @single_movie_id_number = @single_movie_id_number[0]
        endpoint = "movie/#{@single_movie_id_number}"
        api_link = "#{@base_url}/#{endpoint}?api_key=#{@key}&language=en-US"
        require "http"
        @details = HTTP.get(api_link).body


#Get Similar Movies
      endpoint = "movie/#{@single_movie_id}/similar"
      api_address = "#{@base_url}/#{endpoint}?api_key=#{@key}&query=#{@query}&language=en-US"
      require "http"
      @similarvideos = HTTP.get(api_address).body

      # Get Single Movie

      @single_movie_number = [params[:id]]
      @single_movie_number = @single_movie_number[0]
      endpoint = "movie/#{@single_movie_number}/reviews"
      api_link = "#{@base_url}/#{endpoint}?api_key=#{@key}&language=en-US"
      require "http"
      @getreviews = HTTP.get(api_link).body


  end

  def home
#Get Popular Movies
   base_url = "https://api.themoviedb.org/3"
   endpoint = "movie/popular"
   @key = "2517708c8fb4b77b5994719f8007a06d"
   api_url = "#{base_url}/#{endpoint}?api_key=#{@key}&language=en-US"
   require "http"
   @response = HTTP.get(api_url).body
#get genre array
   genre_api_url = "https://api.themoviedb.org/3/genre/movie/list?api_key=2517708c8fb4b77b5994719f8007a06d&language=en-US"
   @genre = JSON.parse(HTTP.get(genre_api_url).body)
  end

  def genre
    # Get Movies by Genre
        @base_url = "https://api.themoviedb.org/3"
        @key = "2517708c8fb4b77b5994719f8007a06d"
        @genre = params[:genre]
        endpoint = "discover/movie"
        api_uri = "#{@base_url}/#{endpoint}?api_key=#{@key}&with_genres=#{@genre}&language=en-US"
        require "http"
        @moviesbygenre = HTTP.get(api_uri).body

        genre_api_url = "https://api.themoviedb.org/3/genre/movie/list?api_key=2517708c8fb4b77b5994719f8007a06d&language=en-US"
        @getgenre = JSON.parse(HTTP.get(genre_api_url).body)

  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_footer.html.erb
<div class="container-fluid">
  <div class="row">
   <div class="large-12 columns" style="background-image: url('/assets/Movie-theater.jpg'); min-height: 200px; width:100%; background-size:cover;">
     <center style="margin-top: 25%;"><%= render "logo" %>
     <hr class="footerdiv"/>
     <p style="color:#fff;">Your Source for movie reviews and information. </p>
     </center>
   </div>
 </div>
</div>

app/views/movies/_header-content.html.erb
<div id="header-items">
  <h1 style="float:left; width: 50%;font-size: 65px;color: #fff;"><a style="color: #fff;" href="/">FLIX<i class="fa fa-video-camera"></i></a></h1>
  <div style = "float:left;text-align: right;margin-top:6px;color: #fff;width: 50%;padding-right: 8px;" id="navbar">

<% if user_signed_in? %>
<h5 style="color#fff;" class="navbar-text pull-right">
  Logged in as <strong><%= current_user.email %></strong>.
  <i class="fa fa-cog"></i> <%= link_to 'Settings', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
</h5>
<% else %>
<h3 style="color#fff;" class="navbar-text pull-right">
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  </h3>
<% end %>

  </div>
</div>

app/views/movies/_logo.html.erb
<h1 style="font-size: 65px;color: #fff;"><a style="color: #fff;" href="/">FLIX<i class="fa fa-video-camera"></i></a></h1>

app/views/movies/_rating.html.erb
<style>
/* Base setup */
@import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);
body {
    margin: 5%;
    background: #111;
    color: #333;
}
h1 {
    font-size: 20px;
    margin-bottom: .5rem;
}

/* Ratings widget */
.rate {
    display: inline-block;
    border: 0;
}
/* Hide radio */
.rate > input {
    display: none;
}
/* Order correctly by floating highest to the right */
.rate > label {
    float: right;
}
/* The star of the show */
.rate > label:before {
    display: inline-block;
    font-size: 1.1rem;
    padding: .3rem .2rem;
    margin: 0;
    cursor: pointer;
    font-family: FontAwesome;
    content: "\f005 "; /* full star */
}
/* Zero stars rating */
.rate > label:last-child:before {
    content: "\f006 "; /* empty star outline */
}
/* Half star trick */
.rate .half:before {
    content: "\f089 "; /* half star no outline */
    position: absolute;
    padding-right: 0;
}
/* Click + hover color */
input:checked ~ label, /* color current and previous stars on checked */
label:hover, label:hover ~ label { color: orange;  } /* color previous stars on hover */

/* Hover highlights */
input:checked + label:hover, input:checked ~ label:hover, /* highlight current and previous stars */
input:checked ~ label:hover ~ label, /* highlight previous selected stars for new rating */
label:hover ~ input:checked ~ label /* highlight previous selected stars */ { color: #c18a24;  }

</style>
<fieldset class="rate">
    <input type="radio" id="rating10" name="rating" value="10" /><label for="rating10" title="5 stars"></label>
    <input type="radio" id="rating9" name="rating" value="9" /><label class="half" for="rating9" title="4 1/2 stars"></label>
    <input type="radio" id="rating8" name="rating" value="8" /><label for="rating8" title="4 stars"></label>
    <input type="radio" id="rating7" name="rating" value="7" /><label class="half" for="rating7" title="3 1/2 stars"></label>
    <input type="radio" id="rating6" name="rating" value="6" /><label for="rating6" title="3 stars"></label>
    <input type="radio" id="rating5" name="rating" value="5" /><label class="half" for="rating5" title="2 1/2 stars"></label>
    <input type="radio" id="rating4" name="rating" value="4" /><label for="rating4" title="2 stars"></label>
    <input type="radio" id="rating3" name="rating" value="3" /><label class="half" for="rating3" title="1 1/2 stars"></label>
    <input type="radio" id="rating2" name="rating" value="2" /><label for="rating2" title="1 star"></label>
    <input type="radio" id="rating1" name="rating" value="1" /><label class="half" for="rating1" title="1/2 star"></label>
    <input type="radio" id="rating0" name="rating" value="0" /><label for="rating0" title="No star"></label>
</fieldset>

app/views/movies/_review_form_api.html.erb
<%= javascript_include_tag( 'closeform.js' ) %>
<%= render 'reviews/form.html.erb' %>

app/views/movies/_write_review.html.erb
<button style="padding: 6px;font-size: 13px;" type="button" class="btn btn-primary col-2" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-star"></i>Write A Review</button>

app/views/movies/addmovie.html.erb
<h1>test</h1>

app/views/movies/genre.html.erb
<% @movie_background_image = [] %>
<% json_object = JSON.parse(@moviesbygenre) %>
<% json_object ['results'].each do |apimovie|%>
<% moviebg = apimovie ['backdrop_path'] %>
<% if moviebg != nil %>
<% @movie_background_image << apimovie['backdrop_path'] %>
<% if @movie_background_image.size == 1 %>
<% break %>
<%= @movie_background_image %>
<% end %>
<% end %>
<% end %>

<% dynamicbg = "https://image.tmdb.org/t/p/w1400_and_h450_face" + @movie_background_image[0].to_s %>
<% fallbackbg = "/assets/movie.jpg" %>

<div class="container-fluid">
  <div class="row">
   <div class="large-12 columns" style="background-image: url('<% if @genre != nil %><%= dynamicbg %><% else %><%= fallbackbg %><% end %>'); min-height: 600px; width:100%; background-size:cover;">
 <%= render "header-content" %>
     <center style="margin-top: 170px;">
         <h2 style="color: #fff;text-shadow: 2px 2px 6px #000000;font-size: 57px;">
           <% if @query_string != nil %>
           <%= "Results For: " + @query_string.capitalize %>
           <% else %>
           <%= "Keyword Search"  %>
              <% end %>
         </h2>
         <form style="width: 40%;" action="/movies">
           <div style="display: inline-flex;" class="form-group">
              <input style="margin-right: 6px; width:325px;" type="text" name="keyword" class="form-control" placeholder="Keyword" value="<%= @query_string %>">
              <button type="submit" class="btn btn-primary">Search</button>
           </div>
         </form>
    </center>
  </div>
 </div>
</div>
<br/>
<div class="container">

<% json_object = JSON.parse(@moviesbygenre) %>
<% json_object ['results'].each do |apimovie|%>
<% movie_title = apimovie['title'] %>
<% movie_img = apimovie['poster_path'] %>
<% description = apimovie['overview'] %>
<% release_date = apimovie['release_date'] %>
<% @id = apimovie['id'] %>
<% genre_ids = apimovie['genre_ids'] %>
<% vote_average = apimovie['vote_average'] %>
<% vote_average = vote_average / 10 * 5 %>
<% @movie_title = apimovie['title'] %>


<div class="container" style=" margin-bottom: 20px;">
   <div class="row" style="background-color:#fff;">
      <div class="col-sm-3">
        <%= image_tag("http://image.tmdb.org/t/p/w185#{movie_img}", :alt => "") %>
      </div>
      <div style="padding-top: 20px;"class="col-sm-8">
        <h3><%= movie_title %> (<%= release_date[0..3]  %>) <% vote_average.to_i.times do %>
          <span style="color: orange;" class="fa fa-star checked"></span>
        <% end %>
        <% black_stars = 5 - vote_average.to_i %>
      <% black_stars.times do %>
      <span style="" class="fa fa-star checked"></span>
    <% end %>
    <% if user_signed_in? %>

  <!-- <span style="background-color: #ff0200; padding: 10px; color: #fff;cursor: pointer; font-size: 15px;position: absolute;top: 0;right: -97px;box-shadow: -1px 2px #888888a6;" onclick="addmovie(<%= @id %>, '<%= @movie_title %>')">Add to Top 3 <i class="fa fa-plus-circle"></i></span> -->
<%= link_to '<i class="fa fa-thumbs-up"></i>'.html_safe, addmovie_path(id:@id), method: "POST", class:"addmovie", remote: true, style: 'background-color: #ff0200; padding: 10px; color: #fff;cursor: pointer; font-size: 15px;position: absolute;top: 0;right: -97px;box-shadow: -1px 2px #888888a6;',:onclick => 'addmovie('+ @id.to_s + ',"'+ @movie_title +'")' %>

  <% end %>
            </h3>

        <div style="margin-top: 5%;margin-bottom: 30px;"><%= description %><%= link_to '...Read More', "movie?id=#{@id}&title=#{movie_title}", options={:style => "color: #ff0200;"} %></div>
        <% genre_ids.each do |genre_item| %>
          <% genre_name = @getgenre["genres"].select { |x| x["id"] == genre_item }[0]["name"] %>
            <span style="background-color: red; padding: 10px;color: #fff;border-radius: 9px;"><a style="color:#fff;" href="<%= "genre?genre=#{genre_item}" %>"><i class="fa fa-tag"></i> <%= genre_name %></a></span>
        <% end %>


        <!-- Button trigger modal -->
        <button style="padding: 6px;font-size: 13px;" type="button" class="btn btn-primary col-2" data-toggle="modal" data-target="<%= "#exampleModalCenter#{@id}" %>"><i class="fa fa-star"></i>Write A Review</button>

        <!-- Modal -->
        <div class="modal fade" id='<%= "exampleModalCenter#{@id}" %>' tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
         <div class="modal-dialog modal-dialog-centered" role="document">
           <div class="modal-content">
             <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLongTitle"><%= "Review: #{movie_title} (#{release_date[0..3]})" %></h5>
               <button id="close_button" type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
               </button>
     </div>
     <div class="modal-body">
<%= render 'review_form_api' %>

     </div>

   </div>
 </div>
</div>
      </div>
  </div>
</div>
<% end %>

</div>
<script type="text/javascript">
function addmovie(id, title){
  alert(title + " has been added to your favorite movies.");
}
</script>
<%= render "footer" %>

app/views/movies/home.html.erb
<% @alert= [params[:alert]] %>
<div class="container-fluid">
  <div class="row">
   <div class="large-12 columns" style="background:linear-gradient(rgba(0, 0, 0, 0.45),rgba(0, 0, 0, 0.45)),url(/assets/movie.jpg); min-height: 600px; width:100%; background-size:cover;">
     <%= render "header-content" %>
     <center style="margin-top: 170px;">
         <h2 style="color: #fff;text-shadow: 2px 2px 6px #000000;font-size: 57px;">
           <% if @query_string != nil %>
           <%= "Results For: " + @query_string.capitalize %>
           <% else %>
           <%= "Keyword Search"  %>
              <% end %>
         </h2>
         <form style="width: 40%;" action="/movies">
           <div style="display: inline-flex;" class="form-group">
              <input style="margin-right: 6px; width:325px;" type="text" name="keyword" class="form-control" placeholder="Keyword" value="<%= @query_string %>">
              <button type="submit" class="btn btn-primary">Search</button>
           </div>
         </form>
    </center>
  </div>
 </div>
</div>
<br/>
<div class="container">
  <h2>Popular Movies</h2>
<% json_object = JSON.parse(@response) %>
<% json_object ['results'].each do |apimovie|%>
<% movie_title = apimovie['title'] %>
<% @movie_title = apimovie['title'] %>
<% movie_img = apimovie['poster_path'] %>
<% description = apimovie['overview'] %>
<% release_date = apimovie['release_date'] %>
<% @id = apimovie['id'] %>
<% genre_ids = apimovie['genre_ids'] %>
<% vote_average = apimovie['vote_average'] %>
<% vote_average = vote_average / 10 * 5 %>
<% @backdrop_path = apimovie['backdrop_path'] %>

<span style="visibility: hidden;" class="top_3"><%= current_user.top_movies if current_user %></span>
<span style="visibility: hidden;" class="movie_id"><%= @id %></span> <span style="visibility: hidden;" class="movie_title"><%= movie_title %></span>

<div class="container" style=" margin-bottom: 20px;">
   <div class="row" style="background-color:#fff;">
      <div class="col-sm-3">
        <%= image_tag("http://image.tmdb.org/t/p/w185#{movie_img}", :alt => "") %>
      </div>
      <div style="padding-top: 20px;"class="col-sm-8">
        <h3><%= movie_title %> (<%= release_date[0..3]  %>) <% vote_average.to_i.times do %>
          <span style="color: orange;" class="fa fa-star checked"></span>
        <% end %>
        <% black_stars = 5 - vote_average.to_i %>
      <% black_stars.times do %>
      <span style="" class="fa fa-star checked"></span>
    <% end %>
    <% if user_signed_in? %>

    <!-- <span style="background-color: #ff0200; padding: 10px; color: #fff;cursor: pointer; font-size: 15px;position: absolute;top: 0;right: -97px;box-shadow: -1px 2px #888888a6;" onclick="addmovie(<%= @id %>, '<%= @movie_title %>')">Add to Top 3 <i class="fa fa-plus-circle"></i></span> -->
  <%= link_to '<i class="fa fa-thumbs-up"></i>'.html_safe, addmovie_path(id:@id), method: "POST", class:"addmovie", remote: true, style: 'background-color: #ff0200; padding: 10px; color: #fff;cursor: pointer; font-size: 15px;position: absolute;top: 0;right: -97px;box-shadow: -1px 2px #888888a6;',:onclick => 'addmovie('+ @id.to_s + ',"'+ @movie_title +'")' %>

    <% end %>
            </h3>

        <div style="margin-top: 5%;margin-bottom: 30px;"><%= description %><%= link_to '...Read More', "movie?id=#{@id}&title=#{movie_title}", options={:style => "color: #ff0200;"} %></div>


        <% genre_ids.each do |genre_item| %>
          <% genre_name = @genre["genres"].select { |x| x["id"] == genre_item }[0]["name"] %>
            <span style="background-color: red; padding: 10px;color: #fff;border-radius: 9px;"><a style="color:#fff" href="<%= "genre?genre=#{genre_item}" %>"><i class="fa fa-tag"></i> <%= genre_name %></a></span>
        <% end %>


        <!-- Button trigger modal -->
        <button style="padding: 6px;font-size: 13px;" type="button" class="btn btn-primary col-2" data-toggle="modal" data-target="<%= "#exampleModalCenter#{@id}" %>"><i class="fa fa-star"></i>Write A Review</button>

        <!-- Modal -->
        <div class="modal fade" id='<%= "exampleModalCenter#{@id}" %>' tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
         <div class="modal-dialog modal-dialog-centered" role="document">
           <div class="modal-content">
             <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLongTitle"><%= "Review: #{movie_title} (#{release_date[0..3]})" %></h5>
               <button id="close_button" type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
               </button>
     </div>
     <div class="modal-body">
<%= render 'review_form_api' %>

     </div>

   </div>
 </div>
</div>
      </div>
  </div>
</div>
<% end %>

</div>
<script type="text/javascript">
function addmovie(id, title){
  alert(title + " has been added to your favorite movies.");
}
</script>
<%= render "footer" %>

app/views/movies/index.html.erb
<% @movie_background_image = [] %>
<% json_object = JSON.parse(@response) %>
<% json_object ['results'].each do |apimovie|%>
<% if apimovie['backdrop_path'] != nil %>
<% @movie_background_image << apimovie['backdrop_path'] %>
<% if @movie_background_image.size == 1 %>
<% break %>
<%= @movie_background_image %>
<% end %>
<% end %>
<% end %>

<% dynamicbg = "https://image.tmdb.org/t/p/w1400_and_h450_face" + @movie_background_image[0].to_s %>
<% fallbackbg = "/assets/movie.jpg" %>

<div class="container-fluid">
  <div class="row">
   <div class="large-12 columns" style="background-image: url('<% if @query_string != nil %><%= dynamicbg %><% else %><%= fallbackbg %><% end %>'); min-height: 600px; width:100%; background-size:cover;">
 <%= render "header-content" %>
     <center style="margin-top: 170px;">
         <h2 style="color: #fff;text-shadow: 2px 2px 6px #000000;font-size: 57px;">
           <% if @query_string != nil %>
           <%= "Results For: " + @query_string.capitalize %>
           <% else %>
           <%= "Keyword Search"  %>
              <% end %>
         </h2>
         <form style="width: 40%;" action="/movies">
           <div style="display: inline-flex;" class="form-group">
              <input style="margin-right: 6px; width:325px;" type="text" name="keyword" class="form-control" placeholder="Keyword" value="<%= @query_string %>">
              <button type="submit" class="btn btn-primary">Search</button>
           </div>
         </form>
    </center>
  </div>
 </div>
</div>
<br/>
<div class="container">
<% @count = -1 %>
<% json_object = JSON.parse(@response) %>
<% json_object ['results'].each do |apimovie|%>
<% @count = @count + 1 %>
<% movie_title = apimovie['title'] %>
<% @movie_title = apimovie['title'] %>
<% movie_img = apimovie['poster_path'] %>
<% description = apimovie['overview'] %>
<% release_date = apimovie['release_date'] %>
<% @id = apimovie['id'] %>
<% genre_ids = apimovie['genre_ids'] %>
<% vote_average = apimovie['vote_average'] %>
<% vote_average = vote_average / 10 * 5 %>


<div class="container" style=" margin-bottom: 20px;">
   <div class="row" style="background-color:#fff;">
      <div class="col-sm-3">
        <%= image_tag("http://image.tmdb.org/t/p/w185#{movie_img}", :alt => "") %>
      </div>
      <div style="padding-top: 20px;"class="col-sm-8">
        <h3><%= movie_title %> (<%= release_date[0..3]  %>) <% vote_average.to_i.times do %>
          <span style="color: orange;" class="fa fa-star checked"></span>
        <% end %>
        <% black_stars = 5 - vote_average.to_i %>
      <% black_stars.times do %>
      <span style="" class="fa fa-star checked"></span>
    <% end %>
    <% if user_signed_in? %>

    <!-- <span style="background-color: #ff0200; padding: 10px; color: #fff;cursor: pointer; font-size: 15px;position: absolute;top: 0;right: -97px;box-shadow: -1px 2px #888888a6;" onclick="addmovie(<%= @id %>, '<%= @movie_title %>')">Add to Top 3 <i class="fa fa-plus-circle"></i></span> -->
  <%= link_to '<i class="fa fa-thumbs-up"></i>'.html_safe, addmovie_path(id:@id), method: "POST", class:"addmovie", remote: true, style: 'background-color: #ff0200; padding: 10px; color: #fff;cursor: pointer; font-size: 15px;position: absolute;top: 0;right: -97px;box-shadow: -1px 2px #888888a6;',:onclick => 'addmovie('+ @id.to_s + ',"'+ @movie_title +'")' %>

    <% end %>
            </h3>

        <div style="margin-top: 5%;margin-bottom: 30px;"><%= description %><%= link_to '...Read More', "movie?id=#{@id}&title=#{movie_title}", options={:style => "color: #ff0200;"} %></div>
        <% genre_ids.each do |genre_item| %>
          <% genre_name = @genre["genres"].select { |x| x["id"] == genre_item }[0]["name"] %>
            <span style="background-color: red; padding: 10px;color: #fff;border-radius: 9px;"><a style="color:#fff;" href="<%= "genre?genre=#{genre_item}" %>"><i class="fa fa-tag"></i> <%= genre_name %></a></span>
        <% end %>


        <!-- Button trigger modal -->
<button style="padding: 6px;font-size: 13px;" type="button" class="btn btn-primary col-2" data-toggle="modal" data-target="<%= "#exampleModalCenter#{@id}" %>"><i class="fa fa-star"></i>Write A Review</button>

<!-- Modal -->
<div class="modal fade" id='<%= "exampleModalCenter#{@id}" %>' tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
 <div class="modal-dialog modal-dialog-centered" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLongTitle"><%= "Review: #{movie_title} (#{release_date[0..3]})" %></h5>
       <button id="close_button" type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
     </div>
     <div class="modal-body">
<%= render 'review_form_api' %>

     </div>

   </div>
 </div>
</div>
</div>
</div>
</div>
<% end %>

</div>
<script type="text/javascript">
function addmovie(id, title){
  alert(title + " has been added to your favorite movies.");
}
</script>
<%= render "footer" %>